apiVersion: v1
kind: Pod
metadata:
  name: cube-cri-load-simple-00000
  namespace: cube-cri-load
  labels:
    app: cube-cri-load
    load-test-batch: batch-000
spec:
  runtimeClassName: cube-load
  terminationGracePeriodSeconds: 0
  containers:
    - name: main
      image: mirror.ccs.tencentyun.com/library/ubuntu:24.04
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 512m
          memory: 512Mi
        limits:
          cpu: 512m
          memory: 512Mi
