FROM ghcr.io/mccutchen/go-httpbin:2.25.0

LABEL org.opencontainers.image.title="go-httpbin for AGR Deployment examples" \
      org.opencontainers.image.source="https://github.com/mccutchen/go-httpbin" \
      org.opencontainers.image.version="v2.25.0"

EXPOSE 8080
