{
 "title": "K6 Sandbox Load Test",
 "tags": [
  "k6",
  "benchmark",
  "sandbox"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"vus\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> count()\n  |> group()"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"vus\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\n  |> group(columns: [\"_time\"])\n  |> sum()\n  |> group()"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"iterations\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> cumulativeSum()\n  |> last()"
    }
   ]
  },
  {
   "title": "Checkpoint Pass Rate",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"checks\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [\"check\"])\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))"
    }
   ]
  },
  {
   "title": "Lifecycle Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_lifecycle_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.75, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_lifecycle_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_lifecycle_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_lifecycle_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column), createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Create Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_create_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.75, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_create_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_create_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_create_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column), createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Token Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"token_acquire_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.75, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"token_acquire_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"token_acquire_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"token_acquire_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column), createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Code Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"code_execute_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.75, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"code_execute_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"code_execute_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"code_execute_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column), createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Delete Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_delete_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.75, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_delete_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.90, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_delete_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column), createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sandbox_delete_duration\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group()\n  |> aggregateWindow(every: 10s, fn: (column, tables=<-) => tables |> quantile(q: 0.99, column: column), createEmpty: false)\n"
    }
   ]
  }
 ]
}